apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: agent-review-request-default-namespace
spec:
  policyName: agent-review-request-default-namespace
  validationActions:
    - Deny
  matchResources:
    resourceRules:
      - apiGroups:
          - example.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - agentreviewrequests
        scope: Namespaced
