apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: agent-review-request-default-namespace
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups:
          - example.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - agentreviewrequests
        scope: Namespaced
  validations:
    - expression: request.namespace == "default"
      message: AgentReviewRequest is supported only in namespace default
