tasks:
  generateCrds:
    action: !com.example.generateCrds
      compilationArtifact: ${module.jar}
      compileClasspath: ${module.compileClasspath}
      outputDir: ${module.rootDir}/resources/META-INF/fabric8

commands:
  - generateCrds
